version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - common
    restart: always

  redis:
    container_name: redis
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - common
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=camngot0102st
    ports:
      - 27017:27017
    networks:
      - common
    restart: always

  cms:
    container_name: cms
    build:
      context: ./cms
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:8080
    networks:
      - common
    restart: always

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: ./Dockerfile
      network: host
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    networks:
      - common
    restart: always

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 4000:4000
    links:
      - redis
      - mongo
    networks:
      - common
    depends_on:
      - redis
      - mongo
    restart: always

networks:
  common:
    driver: bridge
